name: Simple Workflow

on:
  push:
    branches:
      - master

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, GitHub Actions!"
